include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable additional lints
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    use_key_in_widget_constructors: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
